# Generated by Django 3.0.6 on 2020-05-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
