# Generated by Django 3.0.6 on 2020-05-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0002_auto_20200513_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
