# Generated by Django 3.0.6 on 2020-05-14 22:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0003_person_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Win',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 5, 14, 15, 48, 39, 273239))),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm.Person')),
            ],
        ),
    ]
